import mongoose, { Schema } from 'mongoose';
import { IReport } from '../types/report.types';
import {
  applyBaseSchema,
  baseSchemaOptions,
  enumField,
  REPORT_TYPES,
} from '../database';

const urlValidator = {
  validator: (value: string) => !value || /^https?:\/\/.+/.test(value),
  message: 'Must be a valid URL',
};

const reportSchema = new Schema<IReport>(
  {
    reportTitle: {
      type: String,
      required: [true, 'Report title is required'],
      trim: true,
      maxlength: [300, 'Report title cannot exceed 300 characters'],
    },
    reportType: {
      type: String,
      enum: enumField(REPORT_TYPES, 'report type'),
      required: [true, 'Report type is required'],
    },
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    generatedDate: {
      type: Date,
      required: [true, 'Generated date is required'],
      default: Date.now,
    },
    fileUrl: {
      type: String,
      trim: true,
      validate: urlValidator,
    },
    filtersApplied: {
      type: Schema.Types.Mixed,
      default: undefined,
    },
  },
  {
    ...baseSchemaOptions,
    collection: 'reports',
  },
);

applyBaseSchema(reportSchema);

reportSchema.index({ reportType: 1 });
reportSchema.index({ generatedDate: -1 });
reportSchema.index({ generatedBy: 1 });

export const Report = mongoose.model<IReport>('Report', reportSchema);
