'use client';

import { Download, Eye, Loader2, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Pagination } from '@/components/common/Pagination';
import {
  Table,
  TableBody,
  TableCell,
  TableEmpty,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/common/Table';
import { Skeleton } from '@/components/ui/skeleton';
import type { ReportExportFormat, ReportRecord } from '@/types/api-models';
import {
  formatFileSize,
  formatReportDate,
  getReportFormat,
  getReportStatus,
  getStatusBadgeVariant,
  getStatusLabel,
} from '../utils/reports.utils';

interface ReportHistoryTableProps {
  reports: ReportRecord[];
  isLoading?: boolean;
  page: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  onPreview: (report: ReportRecord) => void;
  onDownload: (report: ReportRecord, format?: ReportExportFormat) => void;
  onDelete?: (report: ReportRecord) => void;
  downloadingId?: string | null;
  deletingId?: string | null;
  currentUserId?: string;
}

export function ReportHistoryTable({
  reports,
  isLoading,
  page,
  totalPages,
  onPageChange,
  onPreview,
  onDownload,
  onDelete,
  downloadingId,
  deletingId,
  currentUserId,
}: ReportHistoryTableProps) {
  if (isLoading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-12 w-full" />
        {Array.from({ length: 5 }).map((_, index) => (
          <Skeleton key={index} className="h-14 w-full" />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="hidden md:block">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Name</TableHead>
              <TableHead>Category</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reports.length === 0 ? (
              <TableEmpty colSpan={7}>No reports match your filters.</TableEmpty>
            ) : (
              reports.map((report) => {
                const status = getReportStatus(report);
                const format = getReportFormat(report);

                return (
                  <TableRow key={report._id} className="cursor-pointer" onClick={() => onPreview(report)}>
                    <TableCell className="font-medium">{report.reportTitle}</TableCell>
                    <TableCell>
                      <Badge variant="outline">{report.reportType}</Badge>
                    </TableCell>
                    <TableCell>
                      <Badge variant="secondary">{format === 'unknown' ? '—' : format.toUpperCase()}</Badge>
                    </TableCell>
                    <TableCell className="text-muted">
                      {report.generatedBy === currentUserId ? 'You' : `${report.generatedBy.slice(-6)}`}
                    </TableCell>
                    <TableCell className="text-muted">{formatReportDate(report.generatedDate)}</TableCell>
                    <TableCell>
                      <Badge variant={getStatusBadgeVariant(status)}>{getStatusLabel(status)}</Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1" onClick={(event) => event.stopPropagation()}>
                        <Button variant="ghost" size="icon" onClick={() => onPreview(report)} aria-label="Preview report">
                          <Eye className="size-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          disabled={!report.downloadReady}
                          onClick={() => onDownload(report, format === 'docx' ? 'docx' : 'pdf')}
                          aria-label="Download report"
                        >
                          {downloadingId === report._id ? (
                            <Loader2 className="size-4 animate-spin" />
                          ) : (
                            <Download className="size-4" />
                          )}
                        </Button>
                        {onDelete && (
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => onDelete(report)}
                            aria-label="Delete report"
                            disabled={deletingId === report._id}
                          >
                            {deletingId === report._id ? (
                              <Loader2 className="size-4 animate-spin" />
                            ) : (
                              <Trash2 className="size-4 text-danger" />
                            )}
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </div>

      <div className="grid gap-3 md:hidden">
        {reports.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted">No reports match your filters.</p>
        ) : (
          reports.map((report) => {
            const status = getReportStatus(report);
            const format = getReportFormat(report);
            return (
              <div
                key={report._id}
                className="rounded-xl border border-border bg-card p-4 shadow-soft"
              >
                <button type="button" onClick={() => onPreview(report)} className="w-full text-left">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant="outline">{report.reportType}</Badge>
                    <Badge variant={getStatusBadgeVariant(status)}>{getStatusLabel(status)}</Badge>
                    {format !== 'unknown' && <Badge variant="secondary">{format.toUpperCase()}</Badge>}
                  </div>
                  <p className="mt-2 font-medium">{report.reportTitle}</p>
                  <p className="mt-1 text-sm text-muted">{formatReportDate(report.generatedDate)}</p>
                  {report.fileSizeBytes != null && (
                    <p className="mt-1 text-xs text-muted">{formatFileSize(report.fileSizeBytes)}</p>
                  )}
                </button>
                <div className="mt-3 flex gap-2">
                  <Button size="sm" variant="outline" className="flex-1" onClick={() => onPreview(report)}>
                    Preview
                  </Button>
                  <Button
                    size="sm"
                    className="flex-1"
                    disabled={!report.downloadReady}
                    onClick={() => onDownload(report, format === 'docx' ? 'docx' : 'pdf')}
                  >
                    Download
                  </Button>
                </div>
              </div>
            );
          })
        )}
      </div>

      <Pagination page={page} totalPages={totalPages} onPageChange={onPageChange} />
    </div>
  );
}
